// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC14 - Change Order Status', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC14 - Change Order Status', async function() {
    await driver.get("http://www.onlinecafeteria.com/all_order.html")
    await driver.findElement(By.css("tr:nth-child(1) .fa")).click()
    await driver.findElement(By.id("Editstatus")).click()
    {
      const dropdown = await driver.findElement(By.id("Editstatus"))
      await dropdown.findElement(By.xpath("//option[. = 'Out for Delivery']")).click()
    }
    await driver.findElement(By.id("Editstatus")).click()
    await driver.findElement(By.id("UpdateStatusBtn")).click()
    await driver.wait(until.elementLocated(By.css("tr:nth-child(1) > td:nth-child(7)")), 30000)
    {
      const elements = await driver.findElements(By.css("tr:nth-child(1) > td:nth-child(7)"))
      assert(elements.length)
    }
  })
})
