// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC16 - Edit Menu Item ', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC16 - Edit Menu Item ', async function() {
    await driver.get("http://onlinecafeteria.com/")
    await driver.findElement(By.id("AddToCartBtn")).click()
    await driver.findElement(By.id("admin")).click()
    await driver.findElement(By.id("menu_price64")).click()
    await driver.findElement(By.id("menu_price64")).sendKeys("6.00")
    await driver.findElement(By.id("edit64")).click()
    {
      const elements = await driver.findElements(By.xpath("//tr[4]/td/label"))
      assert(elements.length)
    }
  })
})
