// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC16 - Edit Menu Item ', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC16 - Edit Menu Item ', async function() {
    await driver.get("http://onlinecafeteria.com/place_order.html")
    await driver.findElement(By.id("admin")).click()
    await driver.findElement(By.id("menu_price4")).click()
    await driver.findElement(By.id("menu_price4")).sendKeys("100.00")
    await driver.findElement(By.id("edit4")).click()
    await driver.findElement(By.xpath("//input[@value=\'Place an order\']")).click()
    assert(await driver.findElement(By.xpath("//table[@id=\'cart\']/tbody/tr[9]/td")).getText() == "Price: $100")
    await driver.findElement(By.id("admin")).click()
    await driver.findElement(By.id("menu_price4")).click()
    await driver.findElement(By.id("menu_price4")).sendKeys("7.00")
    await driver.findElement(By.id("edit4")).click()
  })
})
