// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC1 - Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC1 - Login', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.findElement(By.id("name")).sendKeys("Test User")
    await driver.findElement(By.id("phone")).sendKeys("123-456-7891")
    await driver.findElement(By.xpath("//input[@value=\'Log in\']")).click()
    {
      const elements = await driver.findElements(By.xpath("//h1[@id=\'cart_label\']"))
      assert(elements.length)
    }
  })
})
