// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC22.2 - Option To Add Review Is Present', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC22.2 - Option To Add Review Is Present', async function() {
    await driver.get("http://onlinecafeteria.com/place_order.html")
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.id("review 57"))
      assert(elements.length)
    }
  })
})
