// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC22 - User can review item', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC22 - User can review item', async function() {
    await driver.get("http://onlinecafeteria.com/place_order.html")
    await driver.findElement(By.id("review 64")).click()
    await driver.findElement(By.id("add-review2")).click()
    await driver.findElement(By.id("review-input-name")).click()
    await driver.findElement(By.id("review-input-name")).sendKeys("test ")
    await driver.findElement(By.id("review-input-review")).click()
    await driver.findElement(By.id("review-input-review")).sendKeys("test review")
    await driver.findElement(By.id("create-review-with-reviews")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("review 64")).click()
    await driver.sleep(3000)
    {
      const elements = await driver.findElements(By.xpath("//li[contains(.,\'\"test review\"\')]"))
      assert(elements.length)
    }
  })
})
