// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC24c - User Can Remove Recommendations', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC24c - User Can Remove Recommendations', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.findElement(By.id("AddToCartBtn")).click()
    await driver.sleep(2000)
    await driver.findElement(By.id("remove-recIcecream")).click()
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.xpath("//form[@id=\'order\']/div/div[4]/div/div/div"))
      assert(elements.length)
    }
  })
})
