// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC24b - Check Suggested Items Are Akin To Preferences', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC24b - Check Suggested Items Are Akin To Preferences', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.findElement(By.id("ViewPreferencesBtn")).click()
    await driver.findElement(By.name("Dessert")).click()
    await driver.findElement(By.name("Italian")).click()
    await driver.findElement(By.name("Japanese")).click()
    await driver.findElement(By.id("SavePreferencesBtn")).click()
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.id("rec-title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//label[contains(.,\'Icecream\')]"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//label[contains(.,\'Pizza\')]"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//label[contains(.,\'Sushi\')]"))
      assert(elements.length)
    }
  })
})
