// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC25c - User can't select more than three preferences', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC25c - User can't select more than three preferences', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.findElement(By.id("ViewPreferencesBtn")).click()
    await driver.findElement(By.name("Deli")).click()
    await driver.findElement(By.name("Dessert")).click()
    await driver.findElement(By.name("Italian")).click()
    await driver.findElement(By.name("Beverage")).click()
    await driver.findElement(By.id("SavePreferencesBtn")).click()
    assert(await driver.switchTo().alert().getText() == "You can only select up to 3 preferences")
  })
})
