// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC3 - Add a pizza to cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC3 - Add a pizza to cart', async function() {
    await driver.get("http://onlinecafeteria.com//cart.html")
    await driver.setRect(791, 824)
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.findElement(By.id("Pizza")).click()
    await driver.findElement(By.id("Pizza")).sendKeys("1")
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    assert(await driver.findElement(By.xpath("//ul[@id=\'cart\']/li")).getText() == "Item: Pizza\\\\nQuantity: 1")
  })
})
