// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC3 - Add a pizza to cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC3 - Add a pizza to cart', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.findElement(By.id("name")).sendKeys("Test User")
    await driver.findElement(By.id("phone")).sendKeys("123-456-7891")
    await driver.findElement(By.css(".btn-default")).click()
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.findElement(By.id("Pizza")).sendKeys("1")
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.wait(until.elementLocated(By.css("li:nth-child(1)")), 30000)
    {
      const elements = await driver.findElements(By.css("li:nth-child(1)"))
      assert(elements.length)
    }
  })
})
