// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC3b - Add nothing to cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC3b - Add nothing to cart', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.manage().window().setRect(791, 824)
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Place an order:")
  })
})
