// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC6a - Add item twice to cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC6a - Add item twice to cart', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.manage().window().setRect(791, 824)
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.findElement(By.id("Icecream")).sendKeys("2")
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.wait(until.elementLocated(By.css("li")), 30000)
    assert(await driver.findElement(By.css("li")).getText() == "Item: Icecream\\\\nQuantity: 2")
  })
})
