// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC18 - See all orders being delivered', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC18 - See all orders being delivered', async function() {
    await driver.get("http://onlinecafeteria.com/")
    await driver.get("http://onlinecafeteria.com/all_out_for_delivery_orders.html")
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.xpath("//td[contains(.,\'Out for Delivery\')]"))
      assert(elements.length)
    }
  })
})
