// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC19 - See all delivered orders', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC19 - See all delivered orders', async function() {
    await driver.get("http://onlinecafeteria.com/")
    await driver.get("http://onlinecafeteria.com/delivered_orders.html")
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.xpath("//td[contains(.,\'Delivered\')]"))
      assert(elements.length)
    }
  })
})
