// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC1 - Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC1 - Login', async function() {
    await driver.get("http://onlinecafeteria.com//")
    await driver.setRect(791, 824)
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Test User")
    await driver.findElement(By.id("phone")).click()
    await driver.findElement(By.id("phone")).sendKeys("1 (123) 456 7891")
    await driver.findElement(By.css(".btn-default")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Your cart currently has:")
  })
})
