// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC20a - Order details displays status', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC20a - Order details displays status', async function() {
    await driver.get("http://onlinecafeteria.com/cart.html")
    await driver.findElement(By.id("SeeAllOrdersBtn")).click()
    await driver.findElement(By.linkText("View Order")).click()
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.xpath("//b[contains(.,\'Status: \')]"))
      assert(elements.length)
    }
  })
})
