// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC21 - Can see nutrition info', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC21 - Can see nutrition info', async function() {
    await driver.get("http://onlinecafeteria.com/cart.html")
    await driver.findElement(By.id("AddToCartBtn")).click()
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.xpath("//label[contains(.,\'Guidance: diet is based on 2,000 calories a day\')]"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//td[contains(.,\'Calories: 300\')]"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//label[contains(.,\'Ingredients: Eggs, Sugar, Cream, Vanila\')]"))
      assert(elements.length)
    }
  })
})
