// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC23 - Respond To User Review', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC23 - Respond To User Review', async function() {
    await driver.get("http://onlinecafeteria.com/")
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("admin")
    await driver.findElement(By.id("phone")).sendKeys("999-999-9999")
    await driver.findElement(By.css(".btn-default")).click()
    await driver.findElement(By.id("AddToCartBtn")).click()
    await driver.findElement(By.id("review 57")).click()
    await driver.findElement(By.id("add-review2")).click()
    await driver.findElement(By.id("review-input-name")).click()
    await driver.findElement(By.id("review-input-name")).sendKeys("Admin")
    await driver.findElement(By.id("review-input-review")).click()
    await driver.findElement(By.id("review-input-review")).sendKeys("Thanks for the review")
    await driver.findElement(By.id("create-review-with-reviews")).click()
    await driver.sleep(4000)
    await driver.findElement(By.id("review 57")).click()
    await driver.sleep(3000)
    {
      const elements = await driver.findElements(By.xpath("//li[contains(.,\'\"Thanks for the review\"\')]"))
      assert(elements.length)
    }
  })
})
