// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC24a - Suggested Items Is Displayed On Cart Page', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC24a - Suggested Items Is Displayed On Cart Page', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.findElement(By.id("AddToCartBtn")).click()
    {
      const elements = await driver.findElements(By.id("rec-title"))
      assert(elements.length)
    }
  })
})
