// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC24 - User Is Provided Order Recommendations Based Off Preferences', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC24 - User Is Provided Order Recommendations Based Off Preferences', async function() {
    // Test name: TC24 - User Is Provided Order Recommendations Based Off Preferences
    // Step # | name | target | value | comment
    // 1 | open | http://onlinecafeteria.com/index.html |  | 
    await driver.get("http://onlinecafeteria.com/index.html")
    // 2 | click | id=ViewPreferencesBtn |  | 
    await driver.findElement(By.id("ViewPreferencesBtn")).click()
    // 3 | click | name=Dessert |  | 
    await driver.findElement(By.name("Dessert")).click()
    // 4 | click | name=Italian |  | 
    await driver.findElement(By.name("Italian")).click()
    // 5 | click | name=Japanese |  | 
    await driver.findElement(By.name("Japanese")).click()
    // 6 | click | id=SavePreferencesBtn |  | 
    await driver.findElement(By.id("SavePreferencesBtn")).click()
    // 7 | pause | 2000 |  | 
    await driver.sleep(2000)
    // 8 | assertElementPresent | id=rec-title |  | 
    {
      const elements = await driver.findElements(By.id("rec-title"))
      assert(elements.length)
    }
    // 9 | assertElementPresent | xpath=//label[contains(.,'Icecream')] |  | 
    {
      const elements = await driver.findElements(By.xpath("//label[contains(.,\'Icecream\')]"))
      assert(elements.length)
    }
    // 10 | assertElementPresent | xpath=//label[contains(.,'Pizza')] |  | 
    {
      const elements = await driver.findElements(By.xpath("//label[contains(.,\'Pizza\')]"))
      assert(elements.length)
    }
    // 11 | assertElementPresent | xpath=//label[contains(.,'Sushi')] |  | 
    {
      const elements = await driver.findElements(By.xpath("//label[contains(.,\'Sushi\')]"))
      assert(elements.length)
    }
  })
})
