// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC26a - Menu type provides list of types', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC26a - Menu type provides list of types', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.findElement(By.id("name")).sendKeys("admin")
    await driver.findElement(By.id("phone")).sendKeys("999-999-9999")
    await driver.findElement(By.css(".btn-default")).click()
    await driver.findElement(By.id("AddToCartBtn")).click()
    await driver.findElement(By.id("admin")).click()
    await driver.findElement(By.css(".row:nth-child(4) .btn-default")).click()
    {
      const dropdown = await driver.findElement(By.id("type"))
      await dropdown.findElement(By.xpath("//option[. = 'Italian']")).click()
    }
    {
      const elements = await driver.findElements(By.id("type"))
      assert(elements.length)
    }
  })
})
