// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC26 - Owner can categorize food type', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC26 - Owner can categorize food type', async function() {
    await driver.get("http://onlinecafeteria.com/index.html")
    await driver.findElement(By.id("name")).sendKeys("admin")
    await driver.findElement(By.id("phone")).sendKeys("999-999-9999")
    await driver.findElement(By.css(".btn-default")).click()
    await driver.findElement(By.id("AddToCartBtn")).click()
    await driver.findElement(By.id("admin")).click()
    await driver.findElement(By.css(".row:nth-child(4) .btn-default")).click()
    await driver.findElement(By.id("name")).sendKeys("pasta")
    await driver.findElement(By.id("price")).sendKeys("1")
    await driver.findElement(By.id("img_url")).sendKeys("img/pasta.jpg")
    await driver.findElement(By.id("type")).click()
    {
      const dropdown = await driver.findElement(By.id("type"))
      await dropdown.findElement(By.xpath("//option[. = 'Italian']")).click()
    }
    await driver.findElement(By.id("type")).click()
    await driver.findElement(By.id("SubmitNewItemBtn")).click()
    await driver.sleep(3000)
    {
      const elements = await driver.findElements(By.css("tr:nth-child(3) > td:nth-child(8) > label"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.id("menu_type72"))
      assert(elements.length)
    }
  })
})
