// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC2 - Logout', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC2 - Logout', async function() {
    await driver.get("http://onlinecafeteria.com//")
    await driver.setRect(930, 824)
    await driver.findElement(By.xpath("//input[@value=\'Log out\']")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Online Cafeteria")
  })
})
