// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC6.1 - Add pasta twice to cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC6.1 - Add pasta twice to cart', async function() {
    await driver.get("http://onlinecafeteria.com//cart.html")
    await driver.setRect(791, 824)
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.findElement(By.id("Pasta")).click()
    await driver.findElement(By.id("Pasta")).sendKeys("1")
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.wait(until.elementLocated(By.css("h1")), NaN)
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.findElement(By.id("Pasta")).click()
    await driver.findElement(By.id("Pasta")).sendKeys("3")
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    assert(await driver.findElement(By.xpath("//li[contains(.,\'Item: Pasta\\nQuantity: 1\')]")).getText() == "Item: Pasta\\\\nQuantity: 1")
    assert(await driver.findElement(By.xpath("//li[contains(.,\'Item: Pasta\\nQuantity: 3\')]")).getText() == "Item: Pasta\\\\nQuantity: 3")
  })
})
