// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC3.2 - Add invalid quantity', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC3.2 - Add invalid quantity', async function() {
    await driver.get("http://onlinecafeteria.com//cart.html")
    await driver.setRect(791, 824)
    await driver.findElement(By.css("div:nth-child(4) .btn-default")).click()
    await driver.findElement(By.id("Pasta")).click()
    await driver.findElement(By.id("Pasta")).sendKeys("INVALID")
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Place an order:")
  })
})
