// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC3 - Add a pizza to cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC3 - Add a pizza to cart', async function() {
    await driver.get("http://70.37.77.126/cart.html/cart.html")
    await driver.setRect(791, 824)
    await driver.findElement(By.css("div:nth-child(4) .btn-default")).click()
    await driver.findElement(By.id("pizza")).click()
    await driver.findElement(By.id("pizza")).sendKeys("1")
    await driver.findElement(By.css(".row:nth-child(3) .btn-default")).click()
    assert(await driver.findElement(By.css("li:nth-child(1)")).getText() == "Item: Pizza\\\\nQuantity: 1")
  })
})
