// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC6 - Remove pizza from a cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC6 - Remove pizza from a cart', async function() {
    await driver.get("http://70.37.77.126/cart.html")
    await driver.setRect(791, 824)
    await driver.findElement(By.css("div:nth-child(3) .btn-default")).click()
    {
      const element = await driver.findElement(By.css("div:nth-child(4) input"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("226")).click()
    {
      const elements = await driver.findElements(By.xpath("//li[contains(.,\'Item: Pizza\nQuantity: 1\n\n\')]"))
      assert(!elements.length)
    }
  })
})
