// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC8.1 - Verify Total Price', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC8.1 - Verify Total Price', async function() {
    await driver.get("http://onlinecafeteria.com//cart.html")
    await driver.findElement(By.xpath("//input[@value=\'Place order\']")).click()
    assert(await driver.findElement(By.css("li:nth-child(5)")).getText() == " Subtotal: $36.00 ")
  })
})
