// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC8.2 - Pay For Order Invalid Number', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC8.2 - Pay For Order Invalid Number', async function() {
    await driver.get("http://onlinecafeteria.com//cart.html")
    await driver.findElement(By.xpath("//input[@value=\'Place order\']")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.id("credit-card-number")).click()
    await driver.findElement(By.id("credit-card-number")).sendKeys("1111222233334444")
    await driver.findElement(By.id("expiration")).click()
    await driver.findElement(By.id("expiration")).sendKeys("01/23")
    await driver.switchTo().defaultContent()
    await driver.findElement(By.css("fieldset")).click()
    await driver.findElement(By.css(".pure-button")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Pay for your order:")
  })
})
