// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC8.3 - Pay For Order', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC8.3 - Pay For Order', async function() {
    await driver.get("http://onlinecafeteria.com//cart.html")
    await driver.findElement(By.xpath("//input[@value=\'Place order\']")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.id("credit-card-number")).click()
    await driver.findElement(By.id("credit-card-number")).sendKeys("378282246310005")
    await driver.findElement(By.id("expiration")).click()
    await driver.findElement(By.id("expiration")).sendKeys("01/23")
    await driver.switchTo().defaultContent()
    await driver.findElement(By.id("inputAddress")).click()
    await driver.findElement(By.id("inputAddress")).sendKeys("1234 Main St")
    await driver.findElement(By.id("inputCity")).click()
    await driver.findElement(By.id("inputCity")).sendKeys("Philadelphia")
    await driver.findElement(By.id("inputState")).click()
    {
      const dropdown = await driver.findElement(By.id("inputState"))
      await dropdown.findElement(By.xpath("//option[. = 'PA']")).click()
    }
    await driver.findElement(By.id("inputZip")).click()
    await driver.findElement(By.id("inputZip")).sendKeys("19147")
    await driver.findElement(By.id("inputEmail")).click()
    await driver.findElement(By.id("inputEmail")).sendKeys("rosa.ciummo3@gmail.com")
    await driver.findElement(By.xpath("//button[contains(.,\'Submit\')]")).click()
  })
})
