// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC9.1 - Enter invalid email', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC9.1 - Enter invalid email', async function() {
    await driver.get("http://onlinecafeteria.com/cart.html")
    await driver.findElement(By.xpath("//input[@value=\'Place order\']")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.id("credit-card-number")).click()
    await driver.findElement(By.id("credit-card-number")).sendKeys("378282246310005")
    await driver.findElement(By.id("expiration")).click()
    await driver.findElement(By.id("expiration")).sendKeys("01/23")
    await driver.switchTo().defaultContent()
    await driver.findElement(By.css("fieldset")).click()
    await driver.findElement(By.css(".pure-button")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("ThisIsAFake")
    await driver.findElement(By.id("send")).click()
    assert(vars["css=h1"].toString() == "null")
  })
})
