
-- drop table if exists
IF OBJECT_ID('ORDER', 'U') IS NOT NULL DROP TABLE [ORDER];

-- create table
CREATE TABLE [ORDER] (
	ORDER_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONTACT_NAME NVARCHAR(500),
	CONTACT_PHONE NVARCHAR(500), 
	[STATUS] NVARCHAR(100),
	ITEM_1 NVARCHAR(500),
	QUANTITY_1 INT,
	ITEM_2 NVARCHAR(500),
	QUANTITY_2 INT,
	ITEM_3 NVARCHAR(500),
	QUANTITY_3 INT,
	ITEM_4 NVARCHAR(500),
	QUANTITY_4 INT,
	ITEM_5 NVARCHAR(500),
	QUANTITY_5 INT
);
