// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC_2.1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC_2.1', async function() {
    await driver.get("http://70.37.77.126/cart.html")
    await driver.setRect(794, 824)
    await driver.findElement(By.xpath("//input[@value=\'Place an order\']")).click()
    await driver.findElement(By.id("pizza")).sendKeys("1")
    await driver.findElement(By.id("pizza")).click()
    await driver.findElement(By.xpath("//input[@value=\'Add to cart\']")).click()
    await driver.findElement(By.xpath("//input[@value=\'Place an order\']")).click()
    await driver.sleep(3)
    {
      const element = await driver.findElement(By.css(".row:nth-child(4) .btn-default"))
      assert(!await element.isEnabled())
    }
  })
})
